/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── ChurchOS design tokens (exact match from original app) ──────────
        'outline':                  '#757c81',
        'on-tertiary':              '#f7f9ff',
        'surface-tint':             '#515f74',
        'background':               '#f9f9fb',
        'surface-variant':          '#dde3e9',
        'inverse-surface':          '#0c0e10',
        'primary-container':        '#d5e3fd',
        'surface-container-high':   '#e4e9ee',
        'primary-dim':              '#455368',
        'outline-variant':          '#acb3b8',
        'on-primary':               '#f6f7ff',
        'surface-bright':           '#f9f9fb',
        'surface-container':        '#ebeef2',
        'surface':                  '#f9f9fb',
        'on-error':                 '#fff7f6',
        'tertiary-container':       '#cfdef5',
        'primary-fixed':            '#d5e3fd',
        'on-surface':               '#2d3338',
        'tertiary':                 '#526073',
        'secondary-container':      '#d3e4fe',
        'on-primary-container':     '#455367',
        'surface-container-low':    '#f2f4f6',
        'secondary-dim':            '#44546a',
        'on-surface-variant':       '#596065',
        'secondary':                '#506076',
        'primary':                  '#515f74',
        'inverse-on-surface':       '#9c9d9f',
        'on-tertiary-container':    '#414f62',
        'error':                    '#9f403d',
        'on-secondary':             '#f7f9ff',
        'on-secondary-container':   '#435368',
        'secondary-fixed':          '#d3e4fe',
        'surface-dim':              '#d3dbe2',
        'tertiary-dim':             '#465467',
        'on-background':            '#2d3338',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest':'#dde3e9',
        'error-container':          '#fe8983',
        'on-error-container':       '#752121',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter',   'sans-serif'],
        label:    ['Inter',   'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
